---
# tasks file for roles/userland

- hostname:
    name: "{{ hostname }}"
  when:
    hostname is defined
    
- name: Make me feel at home
  package:
    name: "{{ item }}"
    state: latest
  become: "{{ become_bool | default(False)}}"
  with_items:
    - emacs
    - vim
    - tcpdump
    - git
    - zsh
  tags:
    - slow

- command: "which zsh"
  register: which_zsh
- name: Make me a login
  user:
    name: "{{ username }}"
    state: present
    shell: "{{ which_zsh.stdout }}"
    generate_ssh_key: yes
- authorized_key:
    user: "cmd"
    key: "https://github.com/{{ github_id }}.keys"
    manage_dir: yes
    state: present
  when:
    github_id is defined


- name: Add an alias to ~/.ssh/config
  delegate_to: localhost
  with_items: "{{ groups['all'] }}"
  when:
    hostname is defined and ansible_virtualization_type == "NA"
  become: no
  blockinfile:
    block: |
      Host {{ hostname }}
          User cmd
          HostName "{{ hostvars[item]['inventory_hostname'] }}"
    path: "~/.ssh/config"
    backup: "yes"
    state: "present"

