---
- name: Copy source
  hosts: all
  become: "{{ become_bool | default(False) }}"
  tasks:
    - file:
        name: /fortune
        state: directory
      tags:
        - cmd
    - copy:
        src: 02_fortune/fortune/
        dest: /fortune
        owner: www-data
        group: www-data
        mode: 0750
      tags:
        - cmd
  tags:
    - src


- name: Install dependencies
  hosts: all
  become: "{{ become_bool | default(False) }}"
  tasks:
    - apt:
        name: "{{ item }}"
        state: latest
        update_cache: yes
      with_items:
        - python3
        - python3-pip
        - python3-dev
        - virtualenv
      tags:
        - slow
    - pip:
        requirements: /fortune/requirements.txt
        virtualenv: /fortune/venv
        state: latest
        virtualenv_python: python3
      tags:
        - slow
  tags:
    - deps


- name: Start app
  hosts: all
  become: "{{ become_bool | default(False) }}"
  tasks:
    - shell: venv/bin/gunicorn -b 0.0.0.0:80 fortune:app &
      args:
        chdir: /fortune
  tags:
    - app


