---
- name: Frob the widgets
  hosts: all
  tasks:
    - command: /bin/true
    - command: sleep 1
  tags:
    - frob
    
- name: Frob slowly
  hosts: all
  tasks:
    - command: sleep 10
      tags:
        - slow
    - command: /bin/true
  tags:
    - slowfrob
