version: "3"
services:
  alpha:
    image: "python:2.7-jessie"
    container_name: "alpha"
    stdin_open: true
    tty: true

  bravo:
    image: "python:2.7-jessie"
    container_name: "bravo"
    stdin_open: true
    tty: true
