---
- name: Copy source
  hosts: all
  tasks:
    # This relative path will need to be changed if you move the playbook.
    - copy:
        src: ../fortune/
        dest: /fortune
        owner: www-data
        group: www-data
        mode: 0750
  tags:
    - src


- name: Install dependencies
  hosts: all
  tasks:
    - apt:
        name: "{{ item }}"
        state: latest
        update_cache: yes
      with_items:
        - python3
        - python3-pip
        - python3-dev
        - virtualenv
      tags:
        - slow
    - pip:
        requirements: /fortune/requirements.txt
        virtualenv: /fortune/venv
        state: latest
        virtualenv_python: python3
      tags:
        - slow
  tags:
    - deps


- name: Start app
  hosts: all
  tasks:
    - shell: venv/bin/gunicorn -b 0.0.0.0:80 fortune:app &
      args:
        chdir: /fortune
  tags:
    - app


