---
# playbook_simple.yml

- name: One ping only . . .
  hosts: all
  tasks:
    - ping:

- name: Ensure vim and emacs are up-to-date
  hosts: all
  tasks:
    - apt:
        name: "{{ item }}"
        state: latest
        update_cache: yes
      with_items:
        - vim
        - emacs24-nox

