---
# ANSIBLE_ROLES_PATH=roles ansible-galaxy install elastic.elasticsearch
- name: Install Elasticsearch
  hosts: elasticsearch
  tasks:
    - include_role:
        name: elastic.elasticsearch
      vars:
        es_instance_name: "elasticsearch"
        es_version: "5.6.0"
        es_config:
          network.host: "0.0.0.0"
  tags:
    - elasticsearch
    
# - name: Install Kibana
#   hosts: kibana
#   become: yes
#   tasks:
#     - hostname:
#         name: kibana
#   roles:
#     - { role: ansible-role-kibana,
#         kibana_elasticsearch_url: "http://:9200",
#         kibana_version: "5.6.0"
#       }
#   tags:
#     - kibana

# - name: Install Logstash
#   hosts: tag_Role_logstash
#   become: yes
#   tasks:
#     - hostname:
#         name: logstash
#     - include_role:
#         name: ansible-role-java
#     - include_role:
#         name: ansible-role-logstash
#       vars:
#         logstash_elasticsearch_hosts: "http://elasticsearch.rhizalytics.com:9200"
#         logstash_install_plugins: logstash-filter-multiline
#     - copy:
#         src: "../{{item}}"
#         dest: /etc/logstash/conf.d
#       with_items:
#         - 01-syslog-input.conf
#         - 09_docker.conf
#         - 10-syslog.conf
#       notify: "restart logstash"
#       tags:
#         - config
#   handlers:
#     - name: restart_logstash
#       service:
#         name: logstash
#         state: restarted
#       listen: "restart logstash"
#   tags:
#     - logstash

    
# - name: Send all logs to Logstash
#   hosts: tag_cluster_name_elk:!tag_Role_logstash
#   become: yes
#   tasks:
#     - lineinfile:
#         path: /etc/rsyslog.conf
#         line: "*.* @logstash.rhizalytics.com:11514;RSYSLOG_SyslogProtocol23Format"
#         state: present
#       notify: restart_rsyslog
#     - ping:
#   handlers:
#     - name: restart_rsyslog
#       service:
#         name: rsyslog
#         state: restarted
#   tags:
#     - rsyslog

