---
- name: Demonstrate facts and variables
  hosts: all
  tasks:
    - debug:
        msg: "Hello, {{ myname | default('world') }}"
        
    - debug:
        msg: "I am talking to a computer running {{ ansible_distribution }}."

