---
- name: Demonstrate facts and variables
  hosts: all
  tasks:
    - debug:
        msg: "Hello, {{ name | default('world') }}"
        
    - debug:
        msg: "I am running on a computer made by {{ ansible_system_vendor }}."

