---
- name: Determine whether to sudo
  hosts: all
  tasks:
    - set_fact:
        become_bool: True
      when:
        ansible_virtualization_type == "NA" or ansible_virtualization_type == "xen"
    - set_fact:
        become_bool: False
      when:
        ansible_virtualization_type == "docker"
  tags:
    - common
                                       
- name: Copy source
  hosts: all
  become: "{{ become_bool }}"
  tasks:
    # This relative path will need to be changed if you move the playbook.
    - copy:
        src: ../fortune/
        dest: /fortune
        owner: www-data
        group: www-data
        mode: 0750
  tags:
    - src


- name: Install dependencies
  hosts: all
  become: "{{ become_bool }}"
  tasks:
    - apt:
        name: "{{ item }}"
        state: latest
        update_cache: yes
      with_items:
        - apache2
        - python3
        - python3-pip
        - python3-dev
        - virtualenv
      tags:
        - slow
    - pip:
        requirements: /fortune/requirements.txt
        virtualenv: /fortune/venv
        state: latest
        virtualenv_python: python3
      tags:
        - slow
  tags:
    - deps


- name: Start app [Docker]
  hosts: all
  become: False
  tasks:
    - shell: venv/bin/gunicorn -b 0.0.0.0:80 fortune:app &
      args:
        chdir: /fortune
      when: ansible_virtualization_type == "docker"
  tags:
    - app


- name: Start app [native]
  hosts: all
  become: "{{ become_bool }}"
  tasks:
    - file:
        src: /fortune/fortune.service
        dest: /etc/systemd/system/fortune.service
        state: link
      when: ansible_virtualization_type == "NA" or ansible_virtualization_type == "xen"

    - systemd:
        daemon_reload: yes
      when: ansible_virtualization_type == "NA" or ansible_virtualization_type == "xen"

    - service:
        name: fortune
        state: restarted
      when: ansible_virtualization_type == "NA" or ansible_virtualization_type == "xen"

  tags:
    - app

- name: Setup Apache proxy
  hosts: all
  become: "{{ become_bool }}"
  tasks:
    - file:
        path: /etc/htdigest
        owner: www-data
        group: www-data
        mode: 0750
        state: directory
        backup: yes
    - template:
        # This relative path will need to be changed if you move the playbook.
        src: ../fortune.htdigest.j2
        dest: /etc/htdigest/htdigest
        owner: www-data
        group: www-data
        mode: 0640
        backup: yes
    - template:
        # This relative path will need to be changed if you move the playbook.
        src: ../fortune.apache.j2
        dest: /etc/apache2/sites-available/001-fortune.conf
        group: "www-data"
        mode: "0640"
        owner: "www-data"
      notify:
        - restart apache
    - command: a2enmod proxy_http
      args:
        creates: /etc/apache2/mods-enabled/proxy.conf
      notify:
        - restart apache
    - command: a2enmod auth_digest
      args:
        creates: /etc/apache2/mods-enabled/auth_digest.load
      notify:
        - restart apache
    - command: a2ensite 001-fortune
      args:
        creates: /etc/apache2/sites-enabled/001-fortune.conf
      notify:
        - restart apache
  handlers:
    - name: restart apache
      service:
        name: apache2
        state: restarted
  tags:
    - proxy
    
