---
# playbook

- name: Take a variably long time
  gather_facts: no
  hosts: all
  tasks:
    - shell: sleep {{sleeptime}}
    - shell: sleep {{sleeptime}}
    - shell: sleep {{sleeptime}}      
    - debug: msg="Done"
