---
- name: Apply userland role
  hosts: all
  tasks:
    - set_fact:
        become_bool: True
      when:
        ansible_virtualization_type == "NA"
    - set_fact:
        become_bool: False
      when:
        ansible_virtualization_type == "docker"
    - include_vars:
        vault.yml
    - include_role:
        name: userland


