---
- name: Write tmuxinator manifest
  become: no
  hosts: localhost
  tasks:
    - file:
        name: ~/.tmuxinator
        state: directory
    - template:
        src: tmuxinator.yml.j2
        dest: "{{ ansible_env.HOME }}/.tmuxinator/example.yml"
      delegate_to: localhost        
        
